feat: Se termina desarrollo de funcionalidad aprobación multiple de c…
udistrital/cumplidos_dve_cliente pull request #144
Opened 2024-04-05 02:41 UTC by aalejoz25

Se termina funcionalidad de aprobacion multiple de cumplidos, se debe tener en cuenta que:

- La aprobacion multiple esta funcionando por pagina, es decir, si se seleccionan cumplidos en una pagina, pero se cambia a otra, los que estaban previamente seleccionados no se aprobaran al hacer el envio.

2024-04-05 15:09 UTC, ludwinggsanchez requested changes
- Eliminar logs.
- Cambiar llamados a console.error() por alertas claras al usuario.

2024-04-05 16:05 UTC, aalejoz25 commented
> * Eliminar logs.
> * Cambiar llamados a console.error() por alertas claras al usuario.

Se hace el cambio, se eliminan logs y se agregan alertas al usuario

2024-04-05 16:52 UTC, ludwinggsanchez requested changes
Cambiar https://github.com/udistrital/cumplidos_dve_cliente/blob/bca81d7caef86598ee5455c0a7e000d4c2fca772/src/app/pages/aprobacion-supervisor/aprobacion-supervisor.component.ts#L75 por (data && data.userService && data.userService.documento)

2024-04-05 17:14 UTC, criss201x commented
Por favor adjuntar capturas o evidencias del ajuste funcionando.

2024-04-08 14:30 UTC, aalejoz25 commented
![posterior_a_aprobacion](https://github.com/udistrital/cumplidos_dve_cliente/assets/49110446/442109d7-9b63-4ac6-b6cc-3f247c50995f)
> Por favor adjuntar capturas o evidencias del ajuste funcionando y el enlace del RFC tuleap.

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?tracker=600&aid=59789

![seleccion_multiple](https://github.com/udistrital/cumplidos_dve_cliente/assets/49110446/b50d7b8a-2bcb-40a5-b25c-ba50f1b98043)
![aprobacion](https://github.com/udistrital/cumplidos_dve_cliente/assets/49110446/7cc33681-d022-43df-a08b-0e2288917e4a)

2024-04-08 15:19 UTC, merged